spring.application.name=swp

# Spring config import để tự động load file .env (nếu dùng Spring Boot 2.4+)
spring.config.import=optional:file:.env[.properties]

# MySQL Configuration
spring.datasource.url=${MYSQL_URL}
spring.datasource.username=${MYSQL_USER}
spring.datasource.password=${MYSQL_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# OpenAPI / Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# Admin Initial Configuration
admin.username=${ADMIN_USERNAME:admin}
admin.password=${ADMIN_PASSWORD:admin}
admin.dob=${ADMIN_DOB:1990-01-01}
admin.mail=${ADMIN_MAIL:admin@system.com}
admin.phone=${ADMIN_PHONE:0888333666}
admin.gender=${ADMIN_GENDER:MALE}
admin.workplace=${ADMIN_WORKPLACE:System}
